hard = {}
soft = {}
pair = {}

hard[5] = Hash.new("Hit")
hard[6] = Hash.new("Hit")
hard[7] = Hash.new("Hit")
hard[8] = Hash.new("Hit")
hard[8][5] = "Double Down, otherwise Hit"
hard[8][6] = "Double Down, otherwise Hit"
hard[9] = Hash.new("Double Down, otherwise Hit")
hard[9][7] = "Hit"
hard[9][8] = "Hit"
hard[9][9] = "Hit"
hard[9][10] = "Hit"
hard[9]["A"] = "Hit"
hard[10] = Hash.new("Double Down, otherwise Hit")
hard[10][10] = "Hit"
hard[10]["A"] = "Hit"
hard[11] = Hash.new("Double Down, otherwise Hit")
hard[12] = Hash.new("Hit")
hard[12][4] = "Stand"
hard[12][5] = "Stand"
hard[12][6] = "Stay"
hard[13] = Hash.new("Stand")
hard[13][7] =  "Hit"
hard[13][8] =  "Hit"
hard[13][9] =  "Hit"
hard[13][10] = "Hit"
hard[13]["A"] =  "Hit"
hard[14] = Hash.new("Stand")
hard[14][7] =  "Hit"
hard[14][8] =  "Hit"
hard[14][9] =  "Hit"
hard[14][10] = "Hit"
hard[14]["A"] =  "Hit"
hard[15] = Hash.new("Stand")
hard[15][7] =  "Hit"
hard[15][8] =  "Hit"
hard[15][9] =  "Hit"
hard[15][10] = "Hit"
hard[15]["A"] =  "Hit"
hard[16] = Hash.new("Stand")
hard[16][7] = "Hit"
hard[16][8] = "Hit"
hard[16][9] = "Hit"
hard[16][10] = "Hit"
hard[16]["A"] = "Hit"
hard[17] = Hash.new("Stand")
hard[18] = Hash.new("Stand")
hard[19] = Hash.new("Stand")
hard[20] = Hash.new("Stay")

soft[13] = Hash.new("Hit")
soft[13][4] = "Double if possible, otherwise Hit"
soft[13][5] = "Double if possible, otherwise Hit"
soft[13][6] = "Double if possible, otherwise Hit"
soft (14) = Hash.new("Hit")
soft[14][4] = "Double if possible, otherwise Hit"
soft[14][5] = "Double if possible, otherwise Hit"
soft[14][6] = "Double if possible, otherwise Hit"
soft (15) = Hash.new("Hit")
soft[15][4] = "Double if possible, otherwise Hit"
soft[15][5] = "Double if possible, otherwise Hit"
soft[15][6] = "Double if possible, otherwise Hit"
soft (16) = Hash.new("Hit")
soft[16][4] = "Double if possible, otherwise Hit"
soft[16][5] = "Double if possible, otherwise Hit"
soft[16][6] = "Double if possible, otherwise Hit"
soft (17) = Hash.new("Double if possible, otherwise Hit")
soft[17][7] = "Hit"
soft[17][8] = "Hit"
soft[17][9] = "Hit"
soft[17][10] = "Hit"
soft[17][A] = "Hit"
soft (18) = Hash.new("Double if possible, otherwise Stand")
soft[18][2] = "Stand"
soft[18][7] = "Stand"
soft[18][8] = "Stand"
soft[18][9] = "Hit"
soft[18][10] = "Hit"
soft[18][A] = "Stay"
soft[19][6] = "Double if possible, otherwise Stand"
soft[19] = Hash.new("Stand")
soft[20] = Hash.new("Stand")
soft[21] = Hash.new("Stand")

pair[4] = Hash.new("Split")
pair[4][8] = "Hit"
pair[4][9] = "Hit"
pair[4][10] = "Hit"
pair[4][A] = "Hit"
pair[6] = Hash.new("Split")
pair[6][9] = "Hit"
pair[6][10] = "Hit"
pair[6][A] = "Hit"
pair[8] = Hash.new("Split")
pair[8][4] = "Hit"
pair[8][5] = "Hit"
pair[8][6] = "Hit"
pair[10] = Hash.new("Double if possible, otherwise Hit")
pair[10][10] = "Hit"
pair[10][A] = "Hit"
pair[12] = Hash.new("Split")
pair[12][8] = "Hit"
pair[12][9] = "Hit"
pair[12][10] = "Hit"
pair[12][A] = "Hit"
pair[14] = Hash.new("Split")
pair[14][9] = "Hit"
pair[14][A] = "Stand"
pair(16) = Hash.new("Split")
pair[18] = Hash.new("Split")
pair[18][7] = "Stand"
pair[18][10] = "Stand"
pair[18][A] = "Stand"
pair[20] = Hash.new("Stand")
pair[A] = Hash.new("Split")

print soft
print hard
print pair
